config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # view a list of all restaurants
  # get 'restaurants', to: 'restaurants#index'
  # # enter info about a new restaurant and add it to database
  # get 'restaurants/new', to: 'restaurants#new'
  # post 'restaurants', to: 'restaurants#create'
  # # see the details of an individual restaurant
  # get 'restaurants/:id', to: 'restaurants#show', as: :single_restaurant
  # # enter a review about a restaurant and add it to database
  # post 'restaurants/:id/reviews/new', to: 'reviews#create'
  # get 'restaurants/:restaurant_id/reviews', to: 'reviews#new', as: :new_restaurant_review

  resources :restaurants do
    resources :reviews, only: [:create, :new]
  end
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  CATEGORIES = %w[chinese italian japanese french belgian]
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant), status: :see_other # change to path of new rest created
    else
      render :new, status: :unprocessable_entity
    end
    # @restaurant.save
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  # def set_restaurant
  #   @restaurant = Restaurant.find(params[:restaurant_id])
  # end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg p-5 d-flex align-items-md-center justify-content-between">
      <h1 class="navbar-brand "><%= link_to "Yelp MVP", restaurants_path, class: "text-decoration-none text-reset" %></h1>
      <%= link_to "Add a restaurant", new_restaurant_path %>
    </nav>
    <div class="container pt-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<h2>New restaurant</h2>
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h2>Check out all the restaurants!</h2>
<% @restaurants.each do |rest| %>
  <h3><%= link_to rest.name, restaurant_path(rest) %></h3>
  <h4><%= rest.category %></h4>
  <p><%= rest.address %></p>
  <p><%= rest.phone_number %></p>
<% end %>

app/views/restaurants/new.html.erb
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<div class="text-center">
  <h1><%= @restaurant.name %></h1>
  <h3><%= @restaurant.category %></h3>
  <p><%= @restaurant.phone_number %></p>
  <p><%= @restaurant.address %></p>
  <%= link_to "Add a review!", new_restaurant_review_path(@restaurant) %>
  <p><strong>Reviews</strong></p>
  <ul>
    <% @restaurant.reviews.each do |review| %>
      <li><%= review.content %> <span class="bg-info rounded p-1"><%= review.rating %>⭐️</span>
      <%= link_to "Delete", review_path(review), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></li>
    <% end %>
  </ul>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review" %>
<% end %>

app/views/reviews/new.html.erb
<%= render "form", review: @review %>